### ISSUE TITLE
[Suggestion]: Fabric Compat with Extra Alchemy Mod 1.19.2

### ISSUE THREAD

**Issue by AetheriMC** [Fuzss/distinguishedpotions#4]
### Suggestion (Required)

Hello! The [Extra Alchemy](https://www.curseforge.com/minecraft/mc-mods/extra-alchemy) mod adds in several potions that do not currently display the appropriate stoppers when converted into a long or strong potion type. I think the issue is that EA's author went against the standard potion effect naming convention and put their tags at the end of the potion name instead of at the beginning (e.g. extraalchemy:combustion_long).

I know that this issue isn't this mods fault, but I love having the distinguished potion stoppers and icons for alchemy and it's a real shame to not have the same identifying marks for that particular mod.

Thanks in advance!

**Comment by Fuzss** [comment]
I guess I could look into allowing per potion overrides in the config.

**Comment by AetheriMC** [comment]
That would be great, thank you!

**Comment by Fuzss** [comment]
This is possible as of v5.0.0 as strong and long potions are no longer hardcoded, but can instead be specified in the config with regex strings. The system in my Puzzles Lib library to support this unfortunately only exists in 1.19.3+, so it's unlikely there will be a backport to 1.19.2 at some point.
