### ISSUE TITLE
[Bug]: potion effect amplifier bar displaying to the side when the inventory is open

### ISSUE THREAD

**Issue by EnderMelody** [Fuzss/distinguishedpotions#7]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0 Fabric

### Notes (Required)

the option "effect amplifier bar" displays the bar shifted to the left when the inventory is open. this happens in both creative and survival, but displays fine when the inventory is closed.
i tested this with no other mods than this and its library mods.
![image](https://github.com/Fuzss/distinguishedpotions/assets/12649140/677498e8-50c0-4c9a-98a9-9864bc586212)
the option was off by default so im assuming it is known to be broken but just in case i am making a bug report.

**Comment by Fuzss** [comment]
Thanks, fixed in v8.0.1.

**Comment by kckarnige** [comment]
I have this exact issue but with 1.19.4

**Comment by Fuzss** [comment]
1.19.4 is not supported anymore.
